#Specify the version of jdk that you need from docker hub
FROM openjdk:8
#add sampleSpringBoot-0.0.1-SNAPSHOT.jar to the docker container
ADD target/sampleSpringBoot-0.0.1-SNAPSHOT.jar sampleSpringBoot-0.0.1-SNAPSHOT.jar
# the above command will add the jar to the root directory of the container
#expose the port on which this application should run in the container
EXPOSE 8085
#We need to tell the command with which the docker container needs to run our application
ENTRYPOINT ["java", "-jar", "sampleSpringBoot-0.0.1-SNAPSHOT.jar"]
